interface ZIF_BTOCS_DEEPL_CONNECTOR
  public .


  interfaces ZIF_BTOCS_RWS_CONNECTOR .
  interfaces ZIF_BTOCS_UTIL_BASE .

  aliases DESTROY
    for ZIF_BTOCS_RWS_CONNECTOR~DESTROY .
  aliases EXECUTE
    for ZIF_BTOCS_RWS_CONNECTOR~EXECUTE .
  aliases GET_CLIENT
    for ZIF_BTOCS_RWS_CONNECTOR~GET_CLIENT .
  aliases GET_LOGGER
    for ZIF_BTOCS_RWS_CONNECTOR~GET_LOGGER .
  aliases IS_INITIALIZED
    for ZIF_BTOCS_RWS_CONNECTOR~IS_INITIALIZED .
  aliases IS_LOGGER_EXTERNAL
    for ZIF_BTOCS_RWS_CONNECTOR~IS_LOGGER_EXTERNAL .
  aliases NEW_REQUEST
    for ZIF_BTOCS_RWS_CONNECTOR~NEW_REQUEST .
  aliases NEW_RESPONSE
    for ZIF_BTOCS_RWS_CONNECTOR~NEW_RESPONSE .
  aliases SET_ENDPOINT
    for ZIF_BTOCS_RWS_CONNECTOR~SET_ENDPOINT .
  aliases SET_LOGGER
    for ZIF_BTOCS_RWS_CONNECTOR~SET_LOGGER .

  methods API_TRANSLATE
    importing
      !IS_PARAMS type ZBTOCS_DEEPL_S_TRANSLATE_PAR
      !IV_PARSE type ABAP_BOOL
    exporting
      !ES_RESULT type ZBTOCS_DEEPL_S_TRANSLATE_PAR
    returning
      value(RO_RESPONSE) type ref to ZIF_BTOCS_RWS_RESPONSE .
  methods PARSE_TRANSLATE
    importing
      !IO_RESPONSE type ref to ZIF_BTOCS_RWS_RESPONSE
      !IV_SEPARATOR type STRING optional
    returning
      value(RS_RESULT) type ZBTOCS_DEEPL_S_TRANSLATE_RES .
endinterface.
